services:
    dozzle_agent:
      container_name: dozzle_agent
      image: amir20/dozzle:v8.14.9
      command: agent
      restart: unless-stopped
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
      ports:
        - 7007:7007
      healthcheck:
        test: ["CMD", "/dozzle", "healthcheck"]
        interval: 3s
        timeout: 30s
        retries: 5
        start_period: 30s
      env_file: dozzle.env
      networks:
        - dozzle
networks:
  dozzle:
    external: true